baseURL = "https://penguin-note.tech"
languageCode = "en-us"
title = "Penguin's blog"
theme = "notepadium"
copyright = "© 2020. icedpenguin0504"
googleAnalytics = "UA-148005169-2"

[params]
  [params.designer]
    name = "Weru"
    url = "https://www.linkedin.com/in/dan-weru-profile/"

[permalinks]
  posts = "/:filename"

[menu]
  [[menu.main]]
    name = "Categories"
    url = "categories/"
    weight = 9
  [[menu.main]]
    name = "Tags"
    url = "tags/"
    weight = 10
