baseURL = "https://penguin-note.tech"
languageCode = "en-us"
title = "Penguin's blog"
theme = "hugo-swift-theme"
copyright = "© 2020. icedpenguin0504"
googleAnalytics = "UA-148005169-2"

[params]
  author = "icedpenguin0504"
  description = "Note to myself"
  github = "icedpenguin0504"
  twitter = "swimpenguin0504"
  avatar = "https://drive.google.com/uc?export=view&id=1g8VaAqiQTN1hFGOeSpFe9xLAIy-PuR6M"

[permalinks]
  posts = "/:filename"
