baseURL = "https://penguin-note.tech"
languageCode = "en-us"
title = "Penguin's blog"
theme = "notepadium"
copyright = "© 2020. icedpenguin0504"
googleAnalytics = "UA-148005169-2"

[permalinks]
  posts = "/:filename"

# for theme notepadium

[params.syntax]
use = "hljs"  # 1. prismjs 2. hljs 3. none
theme = "nord"
darkTheme = "nord"

[params.nav]
showCategories = true
showTags = true
